### PR TITLE
make readEx test file first, also consider rds file

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Let me quickly rebase that behind your recent commits, or else just squash-merge it.  This was tiny anyway.

**Comment by evanmiller** [comment]
Let me get the tests passing so then I can make sure future PRs pass tests

**Comment by eddelbuettel** [comment]
Yes, having Travis is an excellent idea.

**Comment by evanmiller** [comment]
Okay, tests passing in master now. Feel free to rebase / squash-merge, and fire away with the PRs.

**Comment by eddelbuettel** [comment]
Should be fine now (at the top of your commit graph) and still passed Travis in build [#7](https://travis-ci.org/WizardMac/librdata/builds/337238373).

**Comment by eddelbuettel** [comment]
We probably want to extend them to command-line args but for now the rds example is also hardcoded:

```sh
edd@rob:~/git/librdata(master)$ R --slave -e 'x <- 40:42; saveRDS(x, file="some.rds")'                     
edd@rob:~/git/librdata(master)$ ./readEx             
Read table: (null)        
Read column: (null) with 3 elements of type 1        
Error 0                   
edd@rob:~/git/librdata(master)$ R --slave -e 'x <- as.numeric(40:42); saveRDS(x, file="some.rds")'         
edd@rob:~/git/librdata(master)$ ./readEx 
Read table: (null)        
Read column: (null) with 3 elements of type 2        
Error 0                   
edd@rob:~/git/librdata(master)$                     
```

**Pull request merged**
