### PR TITLE
Add support for reading matrix/table/array dimensions and names

### PR DESCRIPTION
**Pull request by peiyaoli2**
Hi! I added two handlers to achieve this - 

1. dim_handler is called once; it has an array of type RDATA_TYPE_INT32 stored in the data pointer, which contains the dimension of a matrix/table/array. 
2. dim_name_handler is called once for each name in each dimension, the order of the dimension is the same as the order returned by dim_handler. 

For instance, for a 3 rows x 4 columns matrix, dim_handler output is [3, 4]; dim_name_handler will be called 7 times and it spits out the 3 row.names first, followed by the 4 column.names.

(This is also related to #12.)

### CODE REVIEW

**Comment by evanmiller** [comment]
Hi, thank you for the contribution. If you can resolve conflicts with master, I will merge this in. I think the new internal function `read_value_vector_cb` will help you simplify the logic and eliminate the need for the `is_dim` flag.

**Comment by peiyaoli2** [comment]
@evanmiller Hi! I just resolved the conflicts, I hope I didn't break the if-else logic in read_generic_list, with the altrep changes it kinda confuses me

**Comment by evanmiller** [comment]
@peiyaoli2 The ALTREP stuff is kind of crazy – basically it tells R to use an internal or package function to unpack the data. Hopefully your code won't be affected, I'll merge it if the CI checks out.

**Comment by ofajardo** [comment]
@peiyaoli2 great contributions, thanks a lot! Implementing in pyreadr (python bindings) now =)

**Pull request merged**
